management:
  security:
    enabled: false


security:
  basic:
    enabled: false

logging:
  level:
    io:
      pivotal: DEBUG

greeting:
  displayFortune: false

quoteServiceURL: http://quote-service-dev.cfapps/io/quote

greeting:
  displayFortune: true
