management:
  security:
    enabled: false


security:
  basic:
    enabled: false

logging:
  level:
    io:
      pivotal: DEBUG

greeting:
  displayFortune: true 

quoteServiceURL: http://quote-service-dev.cfapps/io/quote
